env:
  global:
    secure:

language: node_js
node_js:
  - "10"
  - "12"

# https://github.com/codecov/example-node
install:
  - npm install
  - npm install -g codecov

script:
  - npm test

after_success:
  - npm report-coverage
