env:
  global:
    secure:

language: node_js
node_js:
  - "10"
  - "12"

# https://github.com/codecov/example-node
install:
  - npm install

script:
  - npm test

after_success:
  - npm run report-coverage
